name: Unit Tests
on:
  pull_request: { }
  push:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Restore Packages
        run: dotnet restore
      
      - name: Startup Docker Components
        run: |
          cd DragonFruit.Data.Queues.Tests
          docker-compose up --detach
        
      - name: Run Unit Tests
        run: dotnet test